/*
    MetNet: comparison of Methabolic Networks
*/
package MetNet.gui;

import MetNet.models.MainModel;
import MetNet.models.MainResults;
import MetNet.models.Utils;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.math.RoundingMode;

/*
MetNet's Main window: starts the comparison and visualize the results
*/
public class MainView extends javax.swing.JFrame implements PropertyChangeListener {
    private OrganismsView orgView;  // link to the previous window
    private MainModel mainModel;    // back end class
    private MainResults results;    // link to the results to be shown
    private String org1; // first organism to be compared
    private String org2; // second organism to be compared
    
    /*
    class constructor: org1 and org2 are the two organisms to be compared
    @param org1: first organism 
    @param org2: second organism
    */
    public MainView(OrganismsView orgView, String org1, String org2) {
        this.orgView = orgView;
        results = new MainResults();   // data structure for the comparison results
        mainModel = new MainModel(org1, org2);
        mainModel.addChangeListener(this);
        initComponents();
        
        // initializing the window table, labels and buttons
        this.org1 = org1;
        this.org2 = org2;
        org1Label.setText(org1);
        org2Label.setText(org2);
        populateCombo();        
        org1Topology.setText(org1 + " topology");
        org2Topology.setText(org2 + " topology");
        org1Topology.setEnabled(false);
        org2Topology.setEnabled(false);
        intersection.setText(org1 + "-" + org2 + " topology comparison");
        intersection.setEnabled(false);
        setVisible(true);
        setSize(845, 645);
        setLocationRelativeTo(null);             
    }
    
    /*
    Values of evt considered:
    stop: sent when the results of the comparison are ready
    */
        @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getNewValue().equals("stop")) {
           enableAll();
           displayResults(); 
          
        }              
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pathwayTable = new javax.swing.JTable();
        organismLabel = new javax.swing.JLabel();
        org1Label = new javax.swing.JLabel();
        org2Label = new javax.swing.JLabel();
        previousButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        combinedSimilarityLabel = new javax.swing.JLabel();
        functionalSimilarityLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        weightedFunctionalSimilarityLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        structureSimilarityLabel = new javax.swing.JLabel();
        org1Topology = new javax.swing.JButton();
        org2Topology = new javax.swing.JButton();
        intersection = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pathwayCombo = new javax.swing.JComboBox();
        pathwayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        pathwayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pathway", "Name", "Structure Similarity", "Pathway Similarity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pathwayTable.setAutoscrolls(false);
        pathwayTable.setEnabled(false);
        pathwayTable.setGridColor(new java.awt.Color(238, 237, 237));
        pathwayTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(pathwayTable);

        organismLabel.setText("Selected organisms:");

        org1Label.setText("jLabel3");

        org2Label.setText("jLabel4");

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setText("MetNet - Comparison of Metabolic Networks");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Global indexes"));

        jLabel4.setText("Pathway similarity:");

        jLabel3.setText("Structure similarity:");

        jLabel6.setText("Combined similarity: ");

        jLabel5.setText("Weighted pathway similarity:");

        org1Topology.setText("jButton1");
        org1Topology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                org1TopologyActionPerformed(evt);
            }
        });

        org2Topology.setText("jButton2");
        org2Topology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                org2TopologyActionPerformed(evt);
            }
        });

        intersection.setText("union");
        intersection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(functionalSimilarityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(weightedFunctionalSimilarityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(structureSimilarityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combinedSimilarityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(org1Topology, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(org2Topology, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intersection, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {combinedSimilarityLabel, functionalSimilarityLabel, structureSimilarityLabel, weightedFunctionalSimilarityLabel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(combinedSimilarityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(structureSimilarityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(functionalSimilarityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(weightedFunctionalSimilarityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(org1Topology)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(org2Topology)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intersection)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {functionalSimilarityLabel, structureSimilarityLabel});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Comparison method"));

        pathwayLabel.setText("pathway");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pathwayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pathwayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathwayLabel)
                    .addComponent(pathwayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(organismLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(org1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(org2Label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(previousButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(startButton))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel8)))
                .addGap(23, 23, 23))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {previousButton, startButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organismLabel)
                    .addComponent(org1Label)
                    .addComponent(org2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousButton)
                    .addComponent(startButton))
                .addGap(9, 9, 9))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {previousButton, startButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        String pathwaymethod = pathwayCombo.getSelectedItem().toString();
        disableAll();
        results = new MainResults();  // results renewed at every comparison
        mainModel.parsingAndComparing(pathwaymethod, results);
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        setVisible(false);
        orgView.normalView();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void org2TopologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_org2TopologyActionPerformed
        try {   
            GraphExplore graph = new GraphExplore(org2, results.getMatrixOrg2(), 1);
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_org2TopologyActionPerformed

    private void org1TopologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_org1TopologyActionPerformed
       try {
            GraphExplore graph = new GraphExplore(org1, results.getMatrixOrg1(), 0);
       } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_org1TopologyActionPerformed

    private void intersectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectionActionPerformed
        try {
            MergeGraphMoreColor graph = new MergeGraphMoreColor(org1, org2, results.getMatrixOrg1(), results.getMatrixOrg2());
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_intersectionActionPerformed

    private void populateCombo() {
        String[] pathMethod = Utils.getPathwayMethod();
        for (int i=0; i< pathMethod.length;i++ )
            pathwayCombo.addItem(pathMethod[i]);
    }    
    
    public void displayResults() {
       // global indexes: rounding to a reasonable number of digits
         BigDecimal CSim = new BigDecimal(results.getCombinedSimIndex()*100);
         BigDecimal SSim = new BigDecimal(results.getStructuralSimIndex()*100);
         BigDecimal FSim = new BigDecimal(results.getPathwaySimIndex()*100);
         BigDecimal WFSim = new BigDecimal(results.getWeightedPathwaySimIndex()*100);
         
       // global indexes visualization 
        setCombinedSimilarityLabel(""+ CSim.setScale(3, RoundingMode.HALF_UP).toString()+"%");
        setStructureSimilarityLabel(""+ SSim.setScale(3, RoundingMode.HALF_UP).toString()+"%");
        setFunctionalSimilarityLabel(""+ FSim.setScale(3, RoundingMode.HALF_UP).toString()+"%");
        setWeightedFunctionalSimilarityLabel(""+ WFSim.setScale(3, RoundingMode.HALF_UP).toString()+"%");
 
        // local indexes visualization
        DefaultTableModel model = (DefaultTableModel)pathwayTable.getModel();
        for (int i = 0; i< results.tableSize(); i++) {
            model.addRow(new Object[]{results.getNameRow(i), results.getDescriptionRow(i), results.getvalueNetworkRow(i), results.getvaluePathwayRow(i)});
            }   
    
    }   

    public void setCombinedSimilarityLabel(String S){
        combinedSimilarityLabel.setText(S);
    }
    
    public void setWeightedFunctionalSimilarityLabel(String S){
        weightedFunctionalSimilarityLabel.setText(S);
    }
    
    public void setStructureSimilarityLabel(String S){
        structureSimilarityLabel.setText(S);
    }
    
        
    public void setFunctionalSimilarityLabel(String S){
        functionalSimilarityLabel.setText(S);
    }
    
    // disabling fields and buttons of the form
    public void disableAll() {
        previousButton.setEnabled(false);
        startButton.setEnabled(false);
        pathwayCombo.setEnabled(false);
        pathwayTable.setEnabled(false);
        org1Topology.setEnabled(false);
        org2Topology.setEnabled(false);
        intersection.setEnabled(false);
    } 
 
    // enabling fiedls and buttons of the form
    public void enableAll() {
        previousButton.setEnabled(true);
        startButton.setEnabled(true);
        pathwayCombo.setEnabled(true);
        pathwayTable.setEnabled(true);
        org1Topology.setEnabled(true);
        org2Topology.setEnabled(true);
        intersection.setEnabled(true);
    } 
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel combinedSimilarityLabel;
    private javax.swing.JLabel functionalSimilarityLabel;
    private javax.swing.JButton intersection;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel org1Label;
    private javax.swing.JButton org1Topology;
    private javax.swing.JLabel org2Label;
    private javax.swing.JButton org2Topology;
    private javax.swing.JLabel organismLabel;
    private javax.swing.JComboBox pathwayCombo;
    private javax.swing.JLabel pathwayLabel;
    private javax.swing.JTable pathwayTable;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel structureSimilarityLabel;
    private javax.swing.JLabel weightedFunctionalSimilarityLabel;
    // End of variables declaration//GEN-END:variables


}
